# Generated by Django 2.2.3 on 2019-09-13 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_link', models.CharField(max_length=100)),
                ('github_link', models.CharField(max_length=100)),
                ('about_me', models.TextField(max_length=800)),
                ('portfolio_photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('technologies', models.TextField(max_length=200)),
                ('deployed_link', models.CharField(max_length=100)),
                ('project_link', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Portfolio')),
                ('project_photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Photo')),
            ],
        ),
    ]
