# Generated by Django 2.2.3 on 2019-09-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190913_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='photo_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
