# Generated by Django 2.2.3 on 2019-09-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190914_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profession',
            field=models.CharField(default='', max_length=20),
        ),
    ]
