# Generated by Django 2.2.3 on 2019-09-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_portfolio_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photo_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profession',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='deployed_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
